# -*- coding: utf-8 -*-
{
    'name': 'Moviles',
    'version': '1.0',
    'category': 'electronica',
    'summary': 'Generated by OdooMaster',
    'description': '''
        This module was automatically generated by OdooMaster.
        Features include:
        - Custom models and views
        - Basic CRUD operations
        - User-friendly interface
    ''',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/movil_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
